# Generated by Django 5.1.2 on 2024-11-29 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('meal_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(blank=True, max_length=100, null=True)),
                ('calories_per_100_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'meal_type',
            },
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('workout_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_workout', models.CharField(blank=True, max_length=50, null=True)),
                ('calories_burned_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'workout_type',
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary_date', models.DateField(blank=True, null=True)),
                ('total_calories_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_calories_burned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_water_intake_ml', models.IntegerField(blank=True, null=True)),
                ('total_sleep_time', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_summary',
                'unique_together': {('user', 'summary_date')},
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_date', models.DateTimeField(blank=True, null=True)),
                ('quantity_in_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('meal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fitnessapp.mealtype')),
            ],
            options={
                'db_table': 'meal',
                'unique_together': {('user', 'meal_type', 'meal_date')},
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('sleep_id', models.AutoField(primary_key=True, serialize=False)),
                ('sleep_time_begin', models.DateTimeField(blank=True, null=True)),
                ('sleep_time_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calories_burned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sleep',
                'unique_together': {('user', 'sleep_time_begin', 'sleep_time_end')},
            },
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('intake_id', models.AutoField(primary_key=True, serialize=False)),
                ('intake_time', models.DateTimeField(blank=True, null=True)),
                ('glasses', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'water_intake',
                'unique_together': {('user', 'intake_time')},
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_time_begin', models.DateTimeField(blank=True, null=True)),
                ('workout_time_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('burned_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('workout_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fitnessapp.workouttype')),
            ],
            options={
                'db_table': 'workout',
                'unique_together': {('user', 'workout_type', 'workout_time_begin', 'workout_time_end')},
            },
        ),
    ]
